@startuml
'https://plantuml.com/class-diagram

!include domain-elements/profile-entity.puml
!include domain-elements/nutzer-class.puml
!include domain-elements/role-enum.puml
!include domain-elements/praesentator-class.puml
!include domain-elements/abstimmung-class.puml
!include domain-elements/kriterien-class.puml
!include domain-elements/wertung-class.puml




Abstimmung "1" .. "n" Kriterien
Nutzer "1" .> "n" Wertung
Wertung "1" .> "n" Kriterien
Nutzer .. Role
Präsentator "1" .> "n" Abstimmung
Profil .. Präsentator

@enduml