@startuml
'https://plantuml.com/class-diagram


class Presentator{
-long_id : int
-name : String
-abstimmung: Abstimmung}

class Nutzer{
-long_id :int
-nick_name : String
}
class Abstimmung{
-long_id : int
-name : String
-kriterien : Kriterien
}
class Kriterien{
-long_id : int
-name : String
-details : String
-wichtung : int
-wertung : Wertung}

class Wertung{
-punkte : decimal}

@enduml