@startuml
'https://plantuml.com/class-diagram



class Nutzer{
-long : id
-String : nick_name
}

enum Role {
TECHNIKER
HR
...
}

entity Profil{
-String : vorname
-String : nachname
-String : email
}

class Präsentator{
-String : name
-abstimmung : Abstimmung
}

class Abstimmung{
-long : id
-String : name

}
class Kriterien{
-long : id
-String : name
-String : details
-int wichtung
-abstimmung : Abstimmung
}

class Wertung{
-kriterien : Kriterien
-decimal : punkte
}

Abstimmung "1" .. "n" Kriterien
Nutzer "1" .> "n" Wertung
Wertung "1" .> "n" Kriterien
Nutzer .. Role
Präsentator "1" .> "n" Abstimmung
Profil .. Präsentator

@enduml